### ISSUE TITLE
manual/detailedTopics/assets/AssetsLess.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#874]
- https://github.com/playframework-ja/translation-project/tree/2.3.5/manual/detailedTopics/assets/AssetsLess.md
- diffs between [2.2.0/manual/detailedTopics/assets/AssetsLess.md](https://github.com/playframework-ja/translation-project/tree/2.2.0/manual/detailedTopics/assets/AssetsLess.md) and [2.3.5/manual/detailedTopics/assets/AssetsLess.md](https://github.com/playframework-ja/translation-project/tree/2.3.5/manual/detailedTopics/assets/AssetsLess.md).

```
--- /Users/garbagetown/Desktop/2.2.0/manual/detailedTopics/assets/AssetsLess.md 2013-09-19 10:11:22.000000000 +0900
+++ //Users/garbagetown/Desktop/2.3.5/manual/detailedTopics/assets/AssetsLess.md    2014-07-28 12:26:38.000000000 +0900
@@ -1,22 +1,28 @@
+<!--- Copyright (C) 2009-2013 Typesafe Inc. <http://www.typesafe.com> -->
 # Using LESS CSS

-[LESS CSS](http://lesscss.org/) is a dynamic stylesheet language. It allows greater flexibility in the way you write CSS files: including support for variables, mixins and more.
+[LESS CSS](http://lesscss.org/) is a dynamic stylesheet language. It allows considerable flexibility in the way you write CSS files including support for variables, mixins and more.

 Compilable assets in Play must be defined in the `app/assets` directory. They are handled by the build process, and LESS sources are compiled into standard CSS files. The generated CSS files are distributed as standard resources into the same `public/` folder as the unmanaged assets, meaning that there is no difference in the way you use them once compiled.

-> Note that managed resources are not copied directly into your application `public` folder, but maintained in a separate folder in `target/scala-2.x.x/resources_managed`.
-
 For example a LESS source file at `app/assets/stylesheets/main.less` will be available as a standard resource at `public/stylesheets/main.css`.

-LESS sources are compiled automatically during a `compile` command, or when you refresh any page in your browser while you are running in development mode. Any compilation errors will be displayed in your browser:
+LESS sources are compiled automatically during an `assets` command, or when you refresh any page in your browser while you are running in development mode. Any compilation errors will be displayed in your browser:

 [[images/lessError.png]]

 ## Working with partial LESS source files

-You can split your LESS source into several libraries, and use the LESS `import` feature. 
+You can split your LESS source into several libraries and use the LESS `import` feature. 
+
+To prevent library files from being compiled individually (or imported) we need them to be skipped by the compiler. To do this partial source files can be prefixed with the underscore (`_`) character, for example: `_myLibrary.less`. The following configuration enables the compiler to ignore partials:
+
+'''scala
+includeFilter in (Assets, LessKeys.less) := "*.less"
+
+excludeFilter in (Assets, LessKeys.less) := "_*.less"
+'''

-To prevent library files from being compiled individually (or imported) we need them to be skipped by the compiler. To do this, partial source files must be prefixed with the underscore (`_`) character, for example: `_myLibrary.less`. To configure this behavior, see the _Configuration_ section at the end of this page.

 ## Layout

@@ -28,43 +34,56 @@
     └ stylesheets
        └ main.less
        └ utils
-          └ _reset.less
-          └ _layout.less    
+          └ reset.less
+          └ layout.less    
 '''

 With the following `main.less` source:

 '''css
-@import "utils/_reset.less";
-@import "utils/_layout.less";
+@import "utils/reset.less";
+@import "utils/layout.less";

 h1 {
     color: red;
 }
 '''

-The resulting CSS file will be compiled as `public/stylesheets/main.css`, and you can use this in your template as any regular public asset. A minified version will also be generated.
+The resulting CSS file will be compiled as `public/stylesheets/main.css` and you can use this in your template as any regular public asset.

 '''html
 <link rel="stylesheet" href="@routes.Assets.at("stylesheets/main.css")">
 '''

-'''html
-<link rel="stylesheet" href="@routes.Assets.at("stylesheets/main.min.css")">
-'''
+## Using LESS with Bootstrap
+
+[Bootstrap](http://getbootstrap.com/css/) is a very popular library used in conjunction with LESS.

-## Configuration
+To use Bootstrap you can use its [WebJar](http://www.webjars.org/) by adding it to your library dependencies. For example, within a `build.sbt` file:

-The default behavior of compiling every file that is not prepended by an underscore may not fit every project; for example if you include a library that has not been designed that way.
+'''scala
+libraryDependencies += "org.webjars" % "bootstrap" % "3.0.2"
+'''

-This can be configured in `project/Build.scala` by overriding the `lessEntryPoints` key. This key holds a `PathFinder`.
+sbt-web will automatically extract WebJars into a lib folder relative to your asset's target folder. Therefore to use Bootstrap you can import relatively e.g.:

-For example, to compile `app/assets/stylesheets/main.less` and nothing else:
+'''less
+@import "lib/bootstrap/less/bootstrap.less";

+h1 {
+  color: @font-size-h1;
+}
 '''
- val main = play.Project(appName, appVersion, appDependencies).settings(
-   lessEntryPoints <<= baseDirectory(_ / "app" / "assets" / "stylesheets" ** "main.less")
- )
+
+## Enablement and Configuration
+
+LESS compilation is enabled by simply adding the plugin to your plugins.sbt file when using the `PlayJava` or `PlayScala` plugins:
+
+'''scala
+addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.0")
 '''

-> **Next:** [[Using Google Closure Compiler | AssetsGoogleClosureCompiler]]
+The plugin's default configuration is normally sufficient. However please refer to the [plugin's documentation](https://github.com/sbt/sbt-less#sbt-less) for information on how it may be configured.
+
+
+> **Next:** [[Linting JavaScript | AssetsJSHint]]

```
